# Generated by Django 5.1.3 on 2025-04-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NelsaApp', '0002_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='seat_number',
            new_name='column',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='bus',
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.IntegerField(default=1),
        ),
    ]
