# Generated by Django 5.1.7 on 2025-04-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NelsaApp', '0003_rename_seat_number_seat_column_remove_seat_bus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
