# Generated by Django 5.1.7 on 2025-04-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NelsaApp', '0004_delete_register_route_duration_route_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Standard', 'Standard'), ('Express', 'Express')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bus',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
