# Generated by Django 5.1.7 on 2025-04-08 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NelsaApp', '0005_bus_is_available_schedule_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='NelsaApp.route'),
        ),
    ]
