# Generated by Django 5.1.7 on 2025-07-02 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NelsaApp', '0009_remove_payment_booking_bookinggroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinggroup',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID for payment verification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='transaction_verified',
            field=models.BooleanField(default=False, help_text='Whether the transaction has been verified by admin'),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
