# Generated by Django 5.1.7 on 2025-10-11 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NelsaApp', '0011_customuser_sms'),
    ]

    operations = [
    ]
