# Generated by Django 5.1.7 on 2026-03-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NelsaApp', '0013_bookinggroup_sms_message_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinggroup',
            name='sms_error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
