# Generated by Django 5.1.7 on 2026-03-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NelsaApp', '0014_bookinggroup_sms_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinggroup',
            name='sms_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='sms_retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
