# Generated by Django 5.1.7 on 2026-03-27 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NelsaApp', '0015_bookinggroup_sms_last_attempt_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('provider', models.CharField(default='GENERIC', max_length=40)),
                ('transaction_id', models.CharField(blank=True, max_length=120, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('booking_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NelsaApp.bookinggroup')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
