# Generated by Django 5.1.7 on 2026-03-27 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NelsaApp', '0017_admin_audit_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinggroup',
            options={'permissions': [('access_admin_bookings', 'Access admin booking management'), ('confirm_bookinggroup', 'Confirm booking groups'), ('cancel_bookinggroup', 'Cancel booking groups'), ('manage_refunds_rebooks', 'Manage refunds and passenger rebooking'), ('view_paymentwebhooks', 'View payment webhook events'), ('view_adminauditlog', 'View admin audit log'), ('manage_routes_schedules', 'Manage routes, schedules, and buses'), ('manage_sms_ops', 'Use SMS dashboard and resend receipts'), ('manage_staff_users', 'Manage Django staff users')]},
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='payment_waived',
            field=models.BooleanField(default=False, help_text='If true, confirmation does not require provider transaction verification (e.g. admin rebook credit).'),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='rebooking_of',
            field=models.ForeignKey(blank=True, help_text='If set, this booking replaces a prior cancelled/rebooked group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebookings', to='NelsaApp.bookinggroup'),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='refund_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='refund_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='refund_status',
            field=models.CharField(choices=[('NONE', 'None'), ('REQUESTED', 'Requested'), ('COMPLETED', 'Completed')], db_index=True, default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='event_kind',
            field=models.CharField(db_index=True, default='payment', help_text='payment or refund (from provider webhook payload).', max_length=20),
        ),
    ]
