# Generated by Django 5.1.7 on 2026-03-31 03:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NelsaApp', '0020_refine_rbac_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=120, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.CharField(default='GENERIC', max_length=40)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='dead_lettered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('BOOKING_CONFIRMED_SMS', 'Booking confirmed SMS'), ('BOOKING_CONFIRMED_EMAIL', 'Booking confirmed email')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('run_after', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_jobs', to='NelsaApp.bookinggroup')),
            ],
            options={
                'ordering': ['run_after', 'id'],
            },
        ),
    ]
