# Generated by Django 5.1.7 on 2026-04-07 15:47

from django.db import migrations, models


def _column_exists(schema_editor, table_name: str, column_name: str) -> bool:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "sqlite":
            cursor.execute(f'PRAGMA table_info("{table_name}")')
            return any(row[1] == column_name for row in cursor.fetchall())
        if connection.vendor == "postgresql":
            cursor.execute(
                """
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = %s
                  AND column_name = %s
                """,
                [table_name.lower(), column_name.lower()],
            )
            return cursor.fetchone() is not None
    # Fallback: try introspection
    with connection.cursor() as cursor:
        if table_name not in connection.introspection.table_names(cursor):
            return False
        desc = connection.introspection.get_table_description(cursor, table_name)
        return any(getattr(d, "name", d[0]) == column_name for d in desc)


def add_customer_notification_status_if_missing(apps, schema_editor):
    """
    Add column only when missing. Production DBs may already have this NOT NULL
    column without a matching Django migration, which caused INSERT failures.
    """
    BookingGroup = apps.get_model("NelsaApp", "BookingGroup")
    table_name = BookingGroup._meta.db_table
    if _column_exists(schema_editor, table_name, "customer_notification_status"):
        return

    field = models.CharField(
        max_length=20,
        choices=[
            ("PENDING", "Pending"),
            ("QUEUED", "Queued"),
            ("SENT", "Sent"),
            ("FAILED", "Failed"),
            ("SKIPPED", "Skipped"),
        ],
        db_index=True,
        default="PENDING",
        help_text="Tracks post-booking customer notifications (email/SMS).",
    )
    field.set_attributes_from_name("customer_notification_status")
    schema_editor.add_field(BookingGroup, field)


class Migration(migrations.Migration):

    dependencies = [
        ("NelsaApp", "0021_paymentwebhooknonce_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="bookinggroup",
                    name="customer_notification_status",
                    field=models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Tracks post-booking customer notifications (email/SMS).",
                        max_length=20,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_customer_notification_status_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
        ),
    ]
