# Generated by Django 5.1.7 on 2026-05-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NelsaApp', '0023_bookinggroup_customer_refund_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
