# Generated by Django 5.1.7 on 2026-05-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NelsaApp', '0024_passenger_phone_allow_duplicates'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinggroup',
            name='whatsapp_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='whatsapp_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='whatsapp_message_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='whatsapp_receipt_code',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='whatsapp_retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='whatsapp_status',
            field=models.CharField(choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='NOT_SENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationjob',
            name='job_type',
            field=models.CharField(choices=[('BOOKING_CONFIRMED_SMS', 'Booking confirmed SMS'), ('BOOKING_CONFIRMED_EMAIL', 'Booking confirmed email'), ('BOOKING_CONFIRMED_WHATSAPP', 'Booking confirmed WhatsApp')], db_index=True, max_length=40),
        ),
    ]
