"""
Django settings for Nelsaproject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import re
from pathlib import Path
from urllib.parse import urlparse
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load Nelsaproject/.env for local dev (secrets stay out of git; see .env.example).
_env_file = BASE_DIR / ".env"
if _env_file.is_file():
    try:
        from dotenv import load_dotenv

        load_dotenv(_env_file, override=False)
    except ImportError:
        pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Environment-first secret key; dev-safe fallback only when env var is not set.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
# Use environment variable to control DEBUG setting
# Default True for local development, False for production/staging
DEPLOYMENT_ENV = os.environ.get('DEPLOYMENT_ENV', 'development').strip().lower()
DEBUG_ENV = os.environ.get('DJANGO_DEBUG')
if DEBUG_ENV is None:
    DEBUG = DEPLOYMENT_ENV == 'development'
else:
    DEBUG = DEBUG_ENV.lower() in ('true', '1', 'yes', 'on')

# Configure ALLOWED_HOSTS from environment variable or use Render-safe defaults
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    # Split comma-separated hosts and strip whitespace
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',') if host.strip()]
else:
    # Defaults that work locally and on Render
    ALLOWED_HOSTS = ['.onrender.com', 'localhost', '127.0.0.1', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'NelsaApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # must be after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'NelsaApp.middleware.RefreshAuthUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Nelsaproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR / 'NelsaApp' / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'NelsaApp.context_processors.site_seo',
                'NelsaApp.context_processors.admin_booking_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'Nelsaproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
def _database_from_env():
    """
    Supports DATABASE_URL for PostgreSQL in production.
    Falls back to local sqlite for development convenience.
    """
    db_url = (os.environ.get("DATABASE_URL", "") or "").strip()
    if not db_url:
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }

    parsed = urlparse(db_url)
    if parsed.scheme not in ("postgres", "postgresql"):
        raise ImproperlyConfigured("Only postgres/postgresql DATABASE_URL is supported in production.")

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": (parsed.path or "").lstrip("/"),
        "USER": parsed.username or "",
        "PASSWORD": parsed.password or "",
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or ""),
        "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "60")),
        "OPTIONS": {"sslmode": os.environ.get("DB_SSLMODE", "prefer")},
    }


DATABASES = {"default": _database_from_env()}
if DEPLOYMENT_ENV in ("production", "staging") and DATABASES["default"]["ENGINE"] == "django.db.backends.sqlite3":
    raise ImproperlyConfigured("SQLite is not supported in production/staging. Set DATABASE_URL to PostgreSQL.")


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Auth redirects: use project login/logout routes instead of Django defaults (/accounts/login/).
LOGIN_URL = '/Login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# WhiteNoise: use non-manifest storage so missing images in templates do not 500 in production
# (Manifest storage requires every {% static %} path to exist after collectstatic.)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
# In local dev, serve directly from static/ (STATICFILES_DIRS) without running collectstatic each time.
WHITENOISE_USE_FINDERS = DEBUG or DEPLOYMENT_ENV == 'development'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration (environment-driven)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes', 'on')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@garanti.local')

# Branding / public URLs (used in emails, QR absolute links — set via environment in production)
COMPANY_NAME = os.environ.get('COMPANY_NAME', 'GARANTI EXPRESS')
COMPANY_SUPPORT_EMAIL = os.environ.get('COMPANY_SUPPORT_EMAIL', DEFAULT_FROM_EMAIL)
# GARANTI fixed contact number (phone, WhatsApp, MoMo instructions, receipts)
COMPANY_SUPPORT_PHONE = os.environ.get('COMPANY_SUPPORT_PHONE', '+237675315422').strip()
if COMPANY_SUPPORT_PHONE and not COMPANY_SUPPORT_PHONE.startswith('+'):
    COMPANY_SUPPORT_PHONE = '+' + COMPANY_SUPPORT_PHONE.lstrip('+')
# Number and account name shown on payment instructions (MTN/Orange “send to this merchant”).
_momo_pay_phone = os.environ.get('PAYMENT_MOMO_MERCHANT_PHONE', '').strip().lstrip('+')
if _momo_pay_phone.startswith('237') and len(_momo_pay_phone) > 3:
    _momo_pay_phone = _momo_pay_phone[3:]
if not _momo_pay_phone:
    _company_digits = re.sub(r'\D', '', COMPANY_SUPPORT_PHONE)
    _momo_pay_phone = _company_digits[3:] if _company_digits.startswith('237') else _company_digits
PAYMENT_MOMO_MERCHANT_PHONE = _momo_pay_phone or '675315422'
_momo_pay_name = os.environ.get('PAYMENT_MOMO_MERCHANT_NAME', 'Doh Nelsa Ijang').strip()
PAYMENT_MOMO_MERCHANT_NAME = _momo_pay_name or 'Doh Nelsa Ijang'
# Prefix for pay-by-reference (e.g. GAR + booking group id).
PAYMENT_REFERENCE_PREFIX = os.environ.get('PAYMENT_REFERENCE_PREFIX', 'GAR')
# Process email/SMS notification jobs immediately after enqueue (no cron needed). Set False on high load workers.
NOTIFICATION_FLUSH_JOBS_INLINE = os.environ.get('NOTIFICATION_FLUSH_JOBS_INLINE', 'True').lower() in (
    'true',
    '1',
    'yes',
    'on',
)
PUBLIC_SITE_URL = os.environ.get('PUBLIC_SITE_URL', 'http://127.0.0.1:8000').rstrip('/')

# Payment webhook security
PAYMENT_WEBHOOK_SECRET = os.environ.get('PAYMENT_WEBHOOK_SECRET', '')
# Optional HMAC of raw body (hex) — header X-Webhook-Body-Signature
PAYMENT_WEBHOOK_HMAC_SECRET = os.environ.get('PAYMENT_WEBHOOK_HMAC_SECRET', '')
PAYMENT_WEBHOOK_MAX_SKEW_SECONDS = int(os.environ.get('PAYMENT_WEBHOOK_MAX_SKEW_SECONDS', '300'))
PAYMENT_WEBHOOK_MAX_RETRIES = int(os.environ.get('PAYMENT_WEBHOOK_MAX_RETRIES', '3'))
PAYMENT_WEBHOOK_TRUSTED_IPS = [
    ip.strip()
    for ip in os.environ.get('PAYMENT_WEBHOOK_TRUSTED_IPS', '').split(',')
    if ip.strip()
]

# Payment provider: manual (merchant MoMo/ORANGE/card instructions + transaction ID) or flutterwave (hosted checkout)
PAYMENT_PROVIDER = os.environ.get('PAYMENT_PROVIDER', 'manual').strip().lower()

# Flutterwave (test keys from https://dashboard.flutterwave.com — use Test mode)
FLUTTERWAVE_PUBLIC_KEY = os.environ.get('FLUTTERWAVE_PUBLIC_KEY', '').strip()
FLUTTERWAVE_SECRET_KEY = os.environ.get('FLUTTERWAVE_SECRET_KEY', '').strip()
FLUTTERWAVE_ENCRYPTION_KEY = os.environ.get('FLUTTERWAVE_ENCRYPTION_KEY', '').strip()
FLUTTERWAVE_CURRENCY = os.environ.get('FLUTTERWAVE_CURRENCY', 'XAF')
# True = local simulate UI when secret key is empty; False = require live/test API keys
FLUTTERWAVE_SIMULATE = os.environ.get('FLUTTERWAVE_SIMULATE', 'True').lower() in ('true', '1', 'yes', 'on')

# Provider-specific webhook signatures (optional, based on provider)
PAYSTACK_WEBHOOK_SECRET = os.environ.get('PAYSTACK_WEBHOOK_SECRET', '')
FLUTTERWAVE_WEBHOOK_HASH = os.environ.get('FLUTTERWAVE_WEBHOOK_HASH', '')

# Ops alerts (comma-separated emails) + webhook failure emails
ALERT_EMAIL_RECIPIENTS = [
    e.strip()
    for e in os.environ.get('ALERT_EMAIL_RECIPIENTS', '').split(',')
    if e.strip()
]
ALERT_ON_WEBHOOK_FAILURE = os.environ.get('ALERT_ON_WEBHOOK_FAILURE', 'False').lower() in (
    'true',
    '1',
    'yes',
    'on',
)

# Internal JSON metrics (token in X-Metrics-Token or ?token=); if unset, staff with webhook perm may access
METRICS_AUTH_TOKEN = os.environ.get('METRICS_AUTH_TOKEN', '')

# Public endpoint throttling defaults (requests per minute)
VERIFY_TICKET_RATE_LIMIT_PER_MIN = int(os.environ.get('VERIFY_TICKET_RATE_LIMIT_PER_MIN', '120'))
VERIFY_SMS_RECEIPT_RATE_LIMIT_PER_MIN = int(os.environ.get('VERIFY_SMS_RECEIPT_RATE_LIMIT_PER_MIN', '60'))
PAYMENT_WEBHOOK_RATE_LIMIT_PER_MIN = int(os.environ.get('PAYMENT_WEBHOOK_RATE_LIMIT_PER_MIN', '120'))

# Alert policy thresholds (ops command uses these values)
ALERT_WEBHOOK_REJECTED_THRESHOLD_5M = int(os.environ.get('ALERT_WEBHOOK_REJECTED_THRESHOLD_5M', '3'))
ALERT_WEBHOOK_DEAD_LETTER_THRESHOLD = int(os.environ.get('ALERT_WEBHOOK_DEAD_LETTER_THRESHOLD', '1'))
ALERT_SMS_FAILED_THRESHOLD = int(os.environ.get('ALERT_SMS_FAILED_THRESHOLD', '20'))
ALERT_PENDING_BOOKINGS_THRESHOLD = int(os.environ.get('ALERT_PENDING_BOOKINGS_THRESHOLD', '100'))
ALERT_ESCALATION_RECIPIENTS = [
    e.strip()
    for e in os.environ.get('ALERT_ESCALATION_RECIPIENTS', '').split(',')
    if e.strip()
]
ONCALL_OWNER = os.environ.get('ONCALL_OWNER', 'ops-team')

# Signed QR ticket tokens (optional separate secret; defaults to SECRET_KEY if unset)
TICKET_SIGNING_SECRET = os.environ.get('TICKET_SIGNING_SECRET', '')
TICKET_MAX_AGE_SECONDS = int(os.environ.get('TICKET_MAX_AGE_SECONDS', str(120 * 24 * 3600)))

# SMS Configuration (all live credentials from environment — no API secrets in code)
SMS_ENABLED = os.environ.get('SMS_ENABLED', 'True').lower() in ('true', '1', 'yes', 'on')
SMS_PROVIDER = os.environ.get('SMS_PROVIDER', 'twilio')  # 'mock', 'twilio', or 'africas_talking' (AT not implemented)
SMS_FROM_NUMBER = os.environ.get('SMS_FROM_NUMBER', '').strip()

# Twilio (required in production when SMS_ENABLED and SMS_PROVIDER=twilio — see _validate_required_env)
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '').strip().strip('"').strip("'")
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '').strip().strip('"').strip("'")
# Your Twilio SMS-capable number in E.164 (e.g. +15551234567). SMS_FROM_NUMBER is accepted as an alias.
TWILIO_PHONE_NUMBER = (
    os.environ.get('TWILIO_PHONE_NUMBER', '').strip().strip('"').strip("'") or SMS_FROM_NUMBER
)
# E.164 or full whatsapp: address, e.g. whatsapp:+14155238886 (Twilio sandbox / Business sender)
TWILIO_WHATSAPP_FROM = os.environ.get('TWILIO_WHATSAPP_FROM', '').strip().strip('"').strip("'")

# WhatsApp booking confirmations (Twilio WhatsApp API — uses passenger phone from booking)
WHATSAPP_ENABLED = os.environ.get('WHATSAPP_ENABLED', 'True').lower() in ('true', '1', 'yes', 'on')
_whatsapp_provider_env = os.environ.get('WHATSAPP_PROVIDER', '').strip().lower()
try:
    from NelsaApp.twilio_config import validate_twilio_whatsapp_credentials

    TWILIO_WHATSAPP_CONFIG_ERROR = validate_twilio_whatsapp_credentials(
        account_sid=TWILIO_ACCOUNT_SID,
        auth_token=TWILIO_AUTH_TOKEN,
        whatsapp_from=TWILIO_WHATSAPP_FROM,
    )
except Exception:
    TWILIO_WHATSAPP_CONFIG_ERROR = None

if _whatsapp_provider_env:
    WHATSAPP_PROVIDER = _whatsapp_provider_env
elif not TWILIO_WHATSAPP_CONFIG_ERROR:
    WHATSAPP_PROVIDER = 'twilio'
else:
    WHATSAPP_PROVIDER = 'mock'
# Default: staff sends receipt via Open WhatsApp from GARANTI number (free, no Twilio).
# Set False only when TWILIO_* credentials are configured for automatic API send.
WHATSAPP_ADMIN_HANDOFF = os.environ.get('WHATSAPP_ADMIN_HANDOFF', 'True').lower() in (
    'true',
    '1',
    'yes',
    'on',
)
# Also send SMS when WhatsApp is enabled (usually leave False)
BOOKING_CONFIRMATION_SMS_ALSO = os.environ.get('BOOKING_CONFIRMATION_SMS_ALSO', 'False').lower() in (
    'true',
    '1',
    'yes',
    'on',
)

# Africa's Talking Configuration (if using Africa's Talking)
AFRICASTALKING_API_KEY = os.environ.get('AFRICASTALKING_API_KEY', '')
AFRICASTALKING_USERNAME = os.environ.get('AFRICASTALKING_USERNAME', '')
AFRICASTALKING_SENDER_ID = os.environ.get('AFRICASTALKING_SENDER_ID', 'NelsaNdo')


def _validate_required_env():
    """
    Enforce critical env vars in production-like environments.
    Keeps local development flexible while protecting real deployments.
    """
    if DEPLOYMENT_ENV not in ('production', 'staging'):
        return

    required = {
        'DJANGO_SECRET_KEY': os.environ.get('DJANGO_SECRET_KEY', ''),
        'EMAIL_HOST_USER': EMAIL_HOST_USER,
        'EMAIL_HOST_PASSWORD': EMAIL_HOST_PASSWORD,
        'DEFAULT_FROM_EMAIL': DEFAULT_FROM_EMAIL,
        'PAYMENT_WEBHOOK_SECRET': PAYMENT_WEBHOOK_SECRET,
        'PUBLIC_SITE_URL': PUBLIC_SITE_URL,
        'COMPANY_SUPPORT_PHONE': COMPANY_SUPPORT_PHONE,
    }

    if SMS_ENABLED and SMS_PROVIDER == 'twilio':
        required.update(
            {
                'TWILIO_ACCOUNT_SID': TWILIO_ACCOUNT_SID,
                'TWILIO_AUTH_TOKEN': TWILIO_AUTH_TOKEN,
                'TWILIO_PHONE_NUMBER': TWILIO_PHONE_NUMBER,
            }
        )

    if WHATSAPP_ENABLED and WHATSAPP_PROVIDER == 'twilio':
        required.update(
            {
                'TWILIO_ACCOUNT_SID': TWILIO_ACCOUNT_SID,
                'TWILIO_AUTH_TOKEN': TWILIO_AUTH_TOKEN,
                'TWILIO_WHATSAPP_FROM': TWILIO_WHATSAPP_FROM,
            }
        )

    missing = [name for name, value in required.items() if not str(value).strip()]
    if missing:
        raise ImproperlyConfigured(
            f"Missing required environment variable(s) for {DEPLOYMENT_ENV}: {', '.join(missing)}"
        )

    if SECRET_KEY == 'dev-only-change-me':
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set to a strong secret in production/staging."
        )


_validate_required_env()

# For development/testing, you can use console backend instead:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Additional settings to prevent 400 errors
# CSRF_TRUSTED_ORIGINS can be set from environment variable or use defaults
CSRF_TRUSTED_ORIGINS_ENV = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if CSRF_TRUSTED_ORIGINS_ENV:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_ENV.split(',')]
else:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'https://*.onrender.com',
    ]
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = False

# Security Settings for Production
if not DEBUG:
    # Security settings for production
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_REDIRECT_EXEMPT = []
    # Disable SSL redirect for development
    SECURE_SSL_REDIRECT = False
    # Disable secure cookies for development
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    X_FRAME_OPTIONS = 'DENY'
    
    # Production logging: stdout only (Render/Heroku/Docker have no persistent logs/ dir).
    # Optional file logging only when LOG_TO_FILE=1 and logs/ exists or is created.
    _log_to_file = os.environ.get("LOG_TO_FILE", "").strip().lower() in ("1", "true", "yes")
    _log_dir = BASE_DIR / "logs"
    if _log_to_file:
        try:
            _log_dir.mkdir(parents=True, exist_ok=True)
        except OSError:
            _log_to_file = False

    if _log_to_file:
        LOGGING = {
            "version": 1,
            "disable_existing_loggers": False,
            "handlers": {
                "console": {"class": "logging.StreamHandler"},
                "file": {
                    "level": "INFO",
                    "class": "logging.FileHandler",
                    "filename": str(_log_dir / "django.log"),
                },
            },
            "root": {"handlers": ["console", "file"], "level": "INFO"},
            "loggers": {
                "django": {"handlers": ["console", "file"], "level": "INFO", "propagate": False},
                "nelsa.audit": {"handlers": ["console", "file"], "level": "INFO", "propagate": False},
                "nelsa.ops": {"handlers": ["console", "file"], "level": "WARNING", "propagate": False},
            },
        }
    else:
        LOGGING = {
            "version": 1,
            "disable_existing_loggers": False,
            "handlers": {
                "console": {
                    "class": "logging.StreamHandler",
                },
            },
            "root": {
                "handlers": ["console"],
                "level": "INFO",
            },
            "loggers": {
                "django": {
                    "handlers": ["console"],
                    "level": "INFO",
                    "propagate": False,
                },
                "nelsa.audit": {
                    "handlers": ["console"],
                    "level": "INFO",
                    "propagate": False,
                },
                "nelsa.ops": {
                    "handlers": ["console"],
                    "level": "WARNING",
                    "propagate": False,
                },
            },
        }
else:
    # Development logging
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'nelsa.audit': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'nelsa.ops': {
                'handlers': ['console'],
                'level': 'WARNING',
                'propagate': False,
            },
        },
    }

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
}
